version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shinomart_db
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"   # в PROD убери/ограничи
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 15

  redis:
    image: redis:7
    container_name: shinomart_redis
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Europe/Moscow
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"   # в PROD убери/ограничи
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 5s
      timeout: 3s
      retries: 15

volumes:
  postgres_data:
  redis_data: